### POSTMAN ou INSOMNIA
### Instalar a extensão REST CLIENT
### Criar um arquivo .http

### Raiz do Projeto
GET http://localhost:5195

### Listar Produtos
GET http://localhost:5195/api/produto/listar

### Buscar produto por nome
GET http://localhost:5195/api/produto/buscar/Gamer

### Cadastrar Produto
POST http://localhost:5195/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Rato",
    "valor" : 43.60
}

### Remover produto por id
DELETE http://localhost:5195/api/produto/remover/ad65d72a-9a59-40ca-be4f-b787a016b823

### Alterar Produto
PUT http://localhost:5195/api/produto/alterar/ad65d72a-9a59-40ca-be4f-b787a016b823
Content-Type: application/json

{
    "nome" : "Mouse"
}